### ISSUE TITLE
*create (cr) name := stmt　の説明が間違っている

### ISSUE THREAD

**Issue by shinsahara** [vdmtools/vdmtools#3]
usermanpp.a4J.pdfで　*create (cr) name := stmt　の説明が間違っているのを発見しました。
「stmt は、オブジェクトを参照する呼出し命令または新しい命令文」となっていますが、「stmt は、 オブジェクトを参照するcall文またはnew式」としなければなりません。

vdmtools/doc-jp/user-man/user_man.tex の修正はしましたが、makeは失敗しました :-)
今、セミナー資料作成に追われているので、深くは追求する時間がありません。

コミット[3c4746b]で、修正したuser_man.texと、Adobe Acrobatで直したPDFファイルをプッシュしました。
PDFファイルは、元が最新かどうかは分かりません :-)

**Comment by mas0061** [comment]
@shinsahara さんの修正でPDFも問題ないと思いますが、一応リビルドして、ついでにCopyrightを2017に修正しました。
